### ISSUE TITLE
Update hackage version

### ISSUE THREAD

**Issue by ghost** [willdonnelly/dyre#25]
Commit 6d8653d5 is crucial to getting Yi working on NixOS. Could you please update the hackage version of Dyre to include this change?

**Comment by IvanMalison** [comment]
It would also be nice to have a release that included a04be85f60cda39b3d57cebb74a25e9508b58160 which fixes #29

**Comment by thkoch2001** [comment]
taffybar also needs a newer version... :-)

**Comment by frasertweedale** [comment]
I have taken maintainership of *dyre* and am working towards a new release.  There's quite a lot I plan to do and a new release may still be a while away.

**Comment by IvanMalison** [comment]
@frasertweedale That's awesome. What sorts of features/issues are you going to be taking on.

What I'd love to see more than anything else is easy support for projects/nix/stack

**Comment by frasertweedale** [comment]
@IvanMalison yes, better support for nix, cabal nix-style builds will happen.
Stack maybe (I don't use it, and in my previous attempts to get Dyre programs to work well in stack environments, frustration exceeded motivation so I stopped).

In particular, Nix support will require recording and comparing file sizes and hashes (because binaries have ctime/mtime of epoch).  This will also help with downgrades, where you install an older version and want the custom binary recompiled accordingly.

**Comment by frasertweedale** [comment]
Well, it happened a lot later than I originally intended, but I released dyre-0.9.0: https://hackage.haskell.org/package/dyre-0.9.0
